# https://taskfile.dev
version: "3"
tasks:
  run: GIN_MODE=release go run ./main.go
  ping: curl http://localhost:8080/ping
  admin:
    cmds:
      - |
        curl -s -X POST 	http://localhost:8080/admin -H 'authorization: Basic Zm9vOmJhcg==' -H 'content-type: application/json' 	-d '{"value":"bar"}' | jq
        echo
        curl -s http://localhost:8080/user/foo | jq

  ## Cross Compile
  build:
    cmds:
      - GOOS=linux GOARCH=amd64 go build -o rel/api-amd64-linux .
      # - GOOS=darwin GOARCH=amd64 go build -o rel/api-amd64-darwin .
  build-hello:
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -o rel/hello-amd64-darwin ./hello
      - GOOS=linux GOARCH=amd64 go build -o rel/hello-amd64-linux ./hello

  test-simple: go test ./simple
  run-hello: go run ./hello
  tidy: go mod tidy
  init-mod: go mod init github.com/cao7113/hello-api
